### ISSUE TITLE
safe_float fails with "0.0"

### ISSUE THREAD

**Issue by divinity76** [theodorejb/PolyCast#1]
safe_float with "0.0", "0.1", etc, makes safe_float return false.
and what is this code about anyway? why is it hardcoded to refuse string floats starting with 0? (which is obviously causing the problem here)

``` php
            if ($val !== "" && $val !== "0" && $val[0] === "0") {
                return false; // reject leading zeros
            }
```

**Comment by theodorejb** [comment]
The intention of this code was to reject integers with leading zeros (like `010`), but it's definitely a bug that it also rejects valid floats like `0.0`. Thanks for noticing this!
